### PR TITLE
Added macOS support

### PR DESCRIPTION
**Pull request by tyfyakov21**
Just as UWP support been added - it would be great to support macOS as well 

Took an inspiration [here](https://github.com/ktonon/react-native-port-patcher/pull/2)

### CODE REVIEW

**Comment by tyfyakov21** [comment]
@ktonon Hi! Sorry for tagging, but could you please review/merge this and push a new version to NPM? Thanks!

**Comment by ktonon** [comment]
Thank you

**Comment by tyfyakov21** [comment]
You are welcome! I noticed that you bumped the package version, but NPM says that 1.0.5 doesn't exist, is there a mistake?

**Comment by ktonon** [comment]
Sorry. Having trouble logging into npm account. Waiting on npm tech support before I can publish...

**Pull request merged**
